apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
        - args:
            - run
            - --allow-net
            - --allow-read
            - --allow-write
            - --allow-env
            - --unstable
            - app/main.ts
          env:
            - name: MONGO_HOST
              value: db-mongodb
            - name: MONGO_URL
              value: mongodb://root:root@db-mongodb:27017
            - name: PORT
              value: "8000"
            - name: RABBITMQ_URL
              value: amqp://guest:guest@service-rabbitmq:5672
            - name: SMTP_HOST
              value: service-maildev
            - name: SMTP_PORT
              value: "1025"
            - name: TZ
              value: Europe/Madrid
          image: denoland/deno:alpine-1.38.0
          name: service-api
          ports:
            - containerPort: 8000
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: api-claim0
      restartPolicy: Always
      volumes:
        - name: api-claim0
          persistentVolumeClaim:
            claimName: api-claim0
status: {}
