apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: root
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
          image: mongo:5
          name: db-mongodb
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/configdb
              name: mongodb-claim0
            - mountPath: /var/lib/mongodb
              name: mongodb-claim1
            - mountPath: /data/db
              name: mongodb-claim2
            - mountPath: /docker-entrypoint-initdb.d
              name: mongodb-claim3
      restartPolicy: Always
      volumes:
        - name: mongodb-claim0
          persistentVolumeClaim:
            claimName: mongodb-claim0
        - name: mongodb-claim1
          persistentVolumeClaim:
            claimName: mongodb-claim1
        - name: mongodb-claim2
          persistentVolumeClaim:
            claimName: mongodb-claim2
        - name: mongodb-claim3
          persistentVolumeClaim:
            claimName: mongodb-claim3
status: {}
