# PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-claim0
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/xvelasqu/Repos/bth-pa2577-bday/config/rabbitmq
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: rabbitmq-claim0
  name: rabbitmq-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
