# PersistentVolume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: worker-claim0
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/xvelasqu/Repos/bth-pa2577-bday/workers
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: worker-claim0
  name: worker-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  volumeName: worker-claim0
  storageClassName: hostpath
  volumeMode: Filesystem
